INSERT INTO new_database.flag (idFlag, flagName, meaning) VALUES (1, 'Я', 'полный рабочий день');
INSERT INTO new_database.flag (idFlag, flagName, meaning) VALUES (2, 'Н', 'отсутствие на рабочее место по невыясненным причинам');
INSERT INTO new_database.flag (idFlag, flagName, meaning) VALUES (3, 'В', 'выходные и праздничные дни');
INSERT INTO new_database.flag (idFlag, flagName, meaning) VALUES (4, 'Рв', 'работа в праздничные и выходные дни а также работа в праздничные и выходные дни, при нахождении в командировке');
INSERT INTO new_database.flag (idFlag, flagName, meaning) VALUES (5, 'Б', 'дни временной нетрудоспособности');
INSERT INTO new_database.flag (idFlag, flagName, meaning) VALUES (6, 'К', 'командировочные дни, а также выходные дни при нахождении в командировке, когда сотрудник отдыхает');
INSERT INTO new_database.flag (idFlag, flagName, meaning) VALUES (7, 'ОТ', 'ежегодный основной оплаченный отпуск');
INSERT INTO new_database.flag (idFlag, flagName, meaning) VALUES (8, 'До', 'неоплачиваемый отпуск (отпуск за свой счет)');
INSERT INTO new_database.flag (idFlag, flagName, meaning) VALUES (9, 'Хд', 'хозяйственный день');
INSERT INTO new_database.flag (idFlag, flagName, meaning) VALUES (10, 'У', 'отпуск на период обучения');
INSERT INTO new_database.flag (idFlag, flagName, meaning) VALUES (11, 'Ож', 'отпуск по уходу за ребенком');